### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by dkfellows** [PRISBteam/DCC_Structural_Design_tool#13]
Building on #11 and #12, it's a very good idea to have your Github Action automation run your tests on every commit. Doing that automatically is great because then you don't forget just because you happened to have bad day for some reason.

Here's an example section (from one of my projects) of `build.yml` to enable that:

```yaml
    - name: Build Project
      uses: threeal/cmake-action@v1.3.0
      with:
        run-build: true
        run-test: true
        test-args: -C Debug
      env:
        CMAKE_BUILD_TYPE: Release
      timeout-minutes: 10
```

Specifically, adding `run-test: true` is the key part.
